owner_id: 125839498150936576
main_server: 125817769923969024

logging:
    gelbooru: ./gelbooru
    e621: ./e621
    sankaku: ./sankaku
    links: ./links
mods:
    vesync:
        credentials: vesync_credentials.txt
        device: f38a4e3f-e936-40a7-9e13-f17edd4626b1



